feat: trigger GHA workflow via CircleCI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -652,6 +652,16 @@ workflows:
               only:
                 - master
 
+      - build-and-publish-snyk-images:
+          name: build and publish snyk images
+          context: team-hammerhead-common-deploy-tokens
+          requires:
+            - upload npm
+          filters:
+            branches:
+              only:
+                - master
+
 ####################################################################################################
 # JOBS
 ####################################################################################################
@@ -1026,3 +1036,26 @@ jobs:
           name: Publish to npm
           command: ./release-scripts/upload-artifacts.sh npm
       - failed-release-notification
+
+  build-and-publish-snyk-images:
+    executor: docker-amd64
+    steps:
+      - prepare-workspace
+      - run:
+          name: Dispatch build-and-publish workflow at snyk-images
+          command: |
+            RESPONSE=$(curl -L \
+              -X POST \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer $HAMMERHEAD_GITHUB_PAT" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              https://api.github.com/repos/snyk/snyk-images/dispatches \
+              -d '{"event_type":"build_and_push_images"}' \
+              -w "%{http_code}" \
+              -o /dev/null)
+            if [ "$RESPONSE" -eq 204 ]; then
+              echo "Successfully triggered the workflow."
+            else
+              echo "Failed to trigger the workflow. HTTP response code: $RESPONSE."
+              exit 1
+            fi
