fix: adding dotnet to linux and osx executors

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -135,6 +135,34 @@ commands:
           paths:
             - ~\AppData\Local\Temp\chocolatey
 
+  install-deps-linux:
+    parameters:
+      dotnet_version:
+        type: string
+        default: '7.0'
+    steps:
+      - restore_cache:
+          key: install-deps-linux-v2-{{ arch }}
+      - run:
+          name: Download and install dotnet
+          command: |
+            if ! command -v dotnet &> /dev/null
+            then
+              echo "dotnet could not be found, downloading and installing"
+              curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel << parameters.dotnet_version >>
+              exit
+            fi
+      - run:
+          name: Save dotnet to path
+          command: echo 'export PATH=~/.dotnet/:${PATH}' >> $BASH_ENV
+      - run:
+          name: Check dotnet version
+          command: dotnet --version
+      - save_cache:
+          key: install-deps-linux-v2-{{ arch }}
+          paths:
+            - ~/.dotnet
+
   install-deps-noop:
     steps:
       - run:
@@ -636,6 +664,7 @@ jobs:
     executor: << parameters.executor >>
     steps:
       - prepare-workspace
+      - install-deps-linux
       - run:
           name: Configuring artifact
           command: << parameters.test_snyk_command >> config set "api=${TEST_SNYK_TOKEN}" # many tests require the token to be in the config
@@ -657,7 +686,7 @@ jobs:
         type: string
       items:
         type: string
-        default: go gradle python elixir composer gradle@6 maven sbt
+        default: go gradle python elixir composer gradle@6 maven sbt dotnet
     executor: << parameters.executor >>
     steps:
       - prepare-workspace
